FROM python:3.10-slim

WORKDIR /app

COPY services/gen-sem-layout/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY services/gen-sem-layout /app

ENV PORT=8001

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
