"""
Room type configurations for constraint solving.
This is a Python version of the TypeScript room-configs.ts
"""

ROOM_TYPE_CONFIGS = {
    'kitchen': {
        'roomType': 'kitchen',
        'name': 'Kitchen',
        'description': 'Kitchen layout with appliances and storage',
        'defaultDimensions': {'width': 4, 'length': 3, 'height': 2.5},
        'categories': [
            {
                'id': 'refrigerator',
                'name': 'Refrigerator',
                'required': True,
                'minCount': 1,
                'maxCount': 1,
                'minSize': [0.6, 1.5, 0.6],
                'maxSize': [1.0, 2.0, 0.8],
                'allowedPositions': 'wall',
                'spacing': {'clearance': 0.1},
            },
            {
                'id': 'sink',
                'name': 'Sink',
                'required': True,
                'minCount': 1,
                'maxCount': 2,
                'minSize': [0.5, 0.2, 0.5],
                'maxSize': [1.2, 0.3, 0.8],
                'allowedPositions': 'wall',
                'dependencies': ['counter'],
            },
            {
                'id': 'stove',
                'name': 'Stove',
                'required': True,
                'minCount': 1,
                'maxCount': 1,
                'minSize': [0.6, 0.9, 0.6],
                'maxSize': [0.9, 1.0, 0.8],
                'allowedPositions': 'wall',
                'spacing': {'minDistance': 0.3, 'clearance': 0.2},
            },
            {
                'id': 'cabinet',
                'name': 'Cabinet',
                'required': False,
                'minCount': 0,
                'maxCount': 10,
                'minSize': [0.3, 0.4, 0.3],
                'maxSize': [1.5, 0.9, 0.6],
                'allowedPositions': 'wall',
            },
            {
                'id': 'counter',
                'name': 'Counter',
                'required': True,
                'minCount': 1,
                'maxCount': 5,
                'minSize': [0.6, 0.9, 0.3],
                'maxSize': [3.0, 1.0, 0.6],
                'allowedPositions': 'wall',
            },
            {
                'id': 'dishwasher',
                'name': 'Dishwasher',
                'required': False,
                'minCount': 0,
                'maxCount': 1,
                'minSize': [0.6, 0.8, 0.6],
                'maxSize': [0.6, 0.9, 0.6],
                'allowedPositions': 'wall',
                'dependencies': ['sink'],
            },
        ],
        'constraints': {
            'minObjects': 3,
            'maxObjects': 15,
            'requiredCategories': ['refrigerator', 'sink', 'stove'],
            'layoutRules': [
                {
                    'id': 'kitchen_triangle',
                    'name': 'Kitchen Work Triangle',
                    'type': 'proximity',
                    'description': 'Refrigerator, sink, and stove should form a triangle',
                    'categoryIds': ['refrigerator', 'sink', 'stove'],
                    'parameters': {'maxDistance': 2.5},
                    'priority': 'recommended',
                },
                {
                    'id': 'sink_counter_proximity',
                    'name': 'Sink-Counter Proximity',
                    'type': 'proximity',
                    'description': 'Sink should be adjacent to counter space',
                    'categoryIds': ['sink', 'counter'],
                    'parameters': {'maxDistance': 0.5},
                    'priority': 'required',
                },
            ],
        },
    },
    'bedroom': {
        'roomType': 'bedroom',
        'name': 'Bedroom',
        'description': 'Bedroom layout with bed and furniture',
        'defaultDimensions': {'width': 4, 'length': 3.5, 'height': 2.5},
        'categories': [
            {
                'id': 'bed',
                'name': 'Bed',
                'required': True,
                'minCount': 1,
                'maxCount': 2,
                'minSize': [1.4, 0.4, 2.0],
                'maxSize': [2.0, 0.6, 2.2],
                'allowedPositions': 'any',
                'spacing': {'clearance': 0.5},
            },
            {
                'id': 'dresser',
                'name': 'Dresser',
                'required': False,
                'minCount': 0,
                'maxCount': 2,
                'minSize': [0.8, 0.6, 0.4],
                'maxSize': [1.5, 1.2, 0.6],
                'allowedPositions': 'wall',
            },
            {
                'id': 'nightstand',
                'name': 'Nightstand',
                'required': False,
                'minCount': 0,
                'maxCount': 2,
                'minSize': [0.4, 0.5, 0.4],
                'maxSize': [0.6, 0.7, 0.5],
                'allowedPositions': 'any',
                'dependencies': ['bed'],
            },
        ],
        'constraints': {
            'minObjects': 1,
            'maxObjects': 8,
            'requiredCategories': ['bed'],
            'layoutRules': [
                {
                    'id': 'bed_accessibility',
                    'name': 'Bed Accessibility',
                    'type': 'accessibility',
                    'description': 'Bed should have clear access from at least one side',
                    'categoryIds': ['bed'],
                    'parameters': {'minClearance': 0.5},
                    'priority': 'required',
                },
            ],
        },
    },
    'bathroom': {
        'roomType': 'bathroom',
        'name': 'Bathroom',
        'description': 'Bathroom layout with fixtures',
        'defaultDimensions': {'width': 2.5, 'length': 2, 'height': 2.5},
        'categories': [
            {
                'id': 'toilet',
                'name': 'Toilet',
                'required': True,
                'minCount': 1,
                'maxCount': 1,
                'minSize': [0.4, 0.4, 0.7],
                'maxSize': [0.5, 0.5, 0.8],
                'allowedPositions': 'wall',
                'spacing': {'clearance': 0.3},
            },
            {
                'id': 'sink',
                'name': 'Sink',
                'required': True,
                'minCount': 1,
                'maxCount': 2,
                'minSize': [0.5, 0.2, 0.4],
                'maxSize': [0.8, 0.3, 0.6],
                'allowedPositions': 'wall',
            },
            {
                'id': 'shower',
                'name': 'Shower',
                'required': False,
                'minCount': 0,
                'maxCount': 1,
                'minSize': [0.8, 0.8, 2.0],
                'maxSize': [1.2, 1.2, 2.5],
                'allowedPositions': 'corner',
                'spacing': {'clearance': 0.2},
            },
            {
                'id': 'bathtub',
                'name': 'Bathtub',
                'required': False,
                'minCount': 0,
                'maxCount': 1,
                'minSize': [1.5, 0.6, 0.7],
                'maxSize': [1.8, 0.7, 0.8],
                'allowedPositions': 'wall',
                'conflicts': ['shower'],
            },
        ],
        'constraints': {
            'minObjects': 2,
            'maxObjects': 6,
            'requiredCategories': ['toilet', 'sink'],
        },
    },
    'living_room': {
        'roomType': 'living_room',
        'name': 'Living Room',
        'description': 'Living room layout with seating and entertainment',
        'defaultDimensions': {'width': 5, 'length': 4, 'height': 2.5},
        'categories': [
            {
                'id': 'sofa',
                'name': 'Sofa',
                'required': False,
                'minCount': 0,
                'maxCount': 2,
                'minSize': [1.8, 0.8, 0.9],
                'maxSize': [2.5, 1.0, 1.0],
                'allowedPositions': 'any',
                'spacing': {'clearance': 0.3},
            },
            {
                'id': 'table',
                'name': 'Coffee Table',
                'required': False,
                'minCount': 0,
                'maxCount': 2,
                'minSize': [0.8, 0.4, 0.8],
                'maxSize': [1.5, 0.5, 1.2],
                'allowedPositions': 'center',
                'dependencies': ['sofa'],
            },
        ],
        'constraints': {
            'minObjects': 0,
            'maxObjects': 10,
        },
    },
    'dining_room': {
        'roomType': 'dining_room',
        'name': 'Dining Room',
        'description': 'Dining room layout',
        'defaultDimensions': {'width': 4, 'length': 3, 'height': 2.5},
        'categories': [
            {
                'id': 'table',
                'name': 'Dining Table',
                'required': True,
                'minCount': 1,
                'maxCount': 1,
                'minSize': [1.2, 0.75, 0.8],
                'maxSize': [2.0, 0.8, 1.5],
                'allowedPositions': 'center',
                'spacing': {'clearance': 0.6},
            },
            {
                'id': 'chair',
                'name': 'Dining Chair',
                'required': False,
                'minCount': 2,
                'maxCount': 8,
                'minSize': [0.4, 0.8, 0.4],
                'maxSize': [0.5, 1.0, 0.5],
                'allowedPositions': 'any',
                'dependencies': ['table'],
            },
        ],
        'constraints': {
            'requiredCategories': ['table'],
        },
    },
    'office': {
        'roomType': 'office',
        'name': 'Office',
        'description': 'Office layout',
        'defaultDimensions': {'width': 3, 'length': 3, 'height': 2.5},
        'categories': [
            {
                'id': 'desk',
                'name': 'Desk',
                'required': True,
                'minCount': 1,
                'maxCount': 2,
                'minSize': [1.2, 0.75, 0.6],
                'maxSize': [2.0, 0.8, 0.8],
                'allowedPositions': 'wall',
            },
            {
                'id': 'chair',
                'name': 'Office Chair',
                'required': True,
                'minCount': 1,
                'maxCount': 2,
                'minSize': [0.5, 1.0, 0.5],
                'maxSize': [0.6, 1.2, 0.6],
                'allowedPositions': 'any',
                'dependencies': ['desk'],
            },
        ],
        'constraints': {
            'requiredCategories': ['desk', 'chair'],
        },
    },
    'closet': {
        'roomType': 'closet',
        'name': 'Closet',
        'description': 'Closet layout',
        'defaultDimensions': {'width': 2, 'length': 1.5, 'height': 2.5},
        'categories': [],
        'constraints': {},
    },
    'other': {
        'roomType': 'other',
        'name': 'Other',
        'description': 'Generic room layout',
        'defaultDimensions': {'width': 4, 'length': 3, 'height': 2.5},
        'categories': [],
        'constraints': {},
    },
}


def get_room_type_config(room_type: str):
    """Get configuration for a room type."""
    return ROOM_TYPE_CONFIGS.get(room_type, ROOM_TYPE_CONFIGS['other'])
